### ISSUE TITLE
adding "--wps" to airodump-ng scan line in order to get information about WPS 

### ISSUE THREAD

**Issue by kcdtv** [SilentGhostX/HT-WPS-Breaker#1]
Hi!
Nice script. :smile_cat: 
I would suggest you to include the <code>--wps</code> argument into your <code>airodump-ng</code> line
It might be interesting too to create another column in the target' selection menu with the information gathered
Like this the users will know if the WPS is present and if it is locked or not
Take care

**Comment by SilentGhostX** [comment]
Hi !
Thank you for your support moral
& thank you brother for your suggestion , i will update the script as soon as possible. 

Date: Tue, 1 Sep 2015 15:25:12 -0700
