### ISSUE TITLE
Problème avec le passage de mes cartes wifi en mode Monitor

### ISSUE THREAD

**Issue by nightyman** [SilentGhostX/HT-WPS-Breaker#2]
Bonjour,

Je tiens tout d'abord à vous féliciter pour votre travail.

Malheureusement j'ai un problème que je veux partager avec toi : 

J'utilise WifiSlax 4.11.1 et je suis en mode live CD/USB. J'ai suivi les étapes de lancement de ton script et il se lance parfaitement.
Mais une fois que je choisis la première option pour commencer une attaque et après la sélection de ma carte wifi, un problème se produit au niveau du basculement de ma carte wifi en mode Monitoring.
Voici ce que j'ai à l'écran : 

---

[+] Scanning for wireless devices ...
[+] We found 2 wireless device(s).

 +----+--------------------------------------+
 | ID |   Interface     |     Chipset        |
 +----+--------------------------------------+
  [01]              ath9k - [phy0]
  [02]              rt2800usb - [phy3]

[+] Select number of wireless device to put into monitor mode [1-2]:1
[ ok ] Mode Monitor is enable .
wlan0mon: unknown interface: No such device
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlan0mon ; No such device.
wlan0mon: unknown interface: No such device

```
 [ ok ] HT-WPS Breaker By Silent Ghost X.

             [+] Try again (Y)es or (N)o : 
```

---

Je ne sais pas où le problème se déclenche.

J'ai essayé de faire passer manuellement mes cartes wifi en mode monitoring (via airmon-zc) ... ma carte wifi interne (du pc portable) marche ... je lance le script et il fonctionne (en zappant le passage de ma carte wifi en mode monitoring) mais quand je l'utilise avec ma carte alfa (AWUS036NH originale) et même en la faisant passer manuellement en mode monitoring le script dépasse l'étape citée ci haut ... mais le scan des réseaux reste vide (j'ai essayé de désactiver ma carte wifi interne et c'est le même problème) !

Si t'as une proposition / solution ... je vous serai reconnaissant.

Merci bien

**Comment by SilentGhostX** [comment]
je vais chercher sur ce problème et je le corrige dès que je peux, mais actuellement, vous pouvez essayer d'activer le mode moniteur manuellement et choisissez la deuxième option dans le script et il est travaillera , et bon chance .

**Comment by nightyman** [comment]
Bonjour,
Merci pour ton retour,
J'ai testé ce matin avec uniquement une carte interne (Atheros) du pc portable et voilà les résultats : 
- En activant manuellement via airmon-zc, le script passe mais après le choix du routeur à attaquer, il se bloque au niveau "Switching mon0 to channel X (canal du routeur)" ! Ensuite plus rien !
- Même chose en sélectionnant la 2ème option ... car je pense que l'origine du problème est le passage (manuellement) en mode monitoring de la carte !

Suggestion : faire fonctionner le script sur la base de airmon-ng (pour switcher les cartes en mode monitoring) au lieu de airmon-zc suffira pour résoudre le problème ? 

Si c'est possible, pourriez vous tester votre script sur la distribution wifislax 4.11.1 (dernière en date). Car malheureusement je n'ai pas assez d'espace sur mon pc pour installer une distribution Kali (où votre script, je pense, travaille sans soucis).

Merci bien encore une fois

**Comment by SilentGhostX** [comment]
Je l'ai réparé le problème maintenant, vous pouvez essayer de nouveau frère et je vous remercie pour avoir signalé le bug, et bonne chance .

**Comment by nightyman** [comment]
Je vous remercie pour votre réactivité. Je testerai ce soir et je vous tiendrai au courant.

**Comment by nightyman** [comment]
Re bonjour,

Désolé d'avoir tarder à vous répondre car j'avais un empêchement.

Malheureusement j'ai retesté votre script et j'ai toujours le même problème ... mais cette fois ci l'option 2 fonctionne à merveille !

 Ci dessous le problème avec la première option :

 +------------------------------+
 | [+] all required arguments   |
 +------------------------------+

 [+]  Switching mon0 to channel 2^C 

*************\* Blocage : Obligé de faire Ctrl+C pour débloquer **************

 +-------------------------------------------+
 | [+] Information about Access Point (AP)   |
 +-------------------------------------------+

 [+] ESSID: TNCAPBACB38
 [+] BSSID: 00:18:E7:BA:CB:38 
 [+] Channel: 2 
 [+] 
 [+] 
 [+] 
 [+] 

 [!] Not all required arguments have been supplied!

```
   [0] Back to list of wireless networks.
   [1] Back to main menu.
   [2] exit.
```

*************\* Passage de ma carte en mode monitoring manuellement ****************

```
        [+] Select one thing from the menu :


 +-------------------------------------------------------------------+
 |  ID  |                      Name                                  |
 +-------------------------------------------------------------------+
 | [01] | Enable The Monitor Mode .                                  |
 | [02] | Disable The Monitor Mode .                                 |
 | [03] | Back to menu .                                             |
 +-------------------------------------------------------------------+

 [!] Type the ID of your choice : 1
```

[+] Scanning for wireless devices ...
[+] We found 1 wireless device(s).

 +----+--------------------------------------+
 | ID |   Interface     |     Chipset        |
 +----+--------------------------------------+
  [01]              ath9k - [phy0]

[+] Select number of wireless device to put into monitor mode [1-1]:1
[ ok ] Mode Monitor is enable .
wlan0mon: unknown interface: No such device
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlan0mon ; No such device.
wlan0mon: unknown interface: No such device

```
 [ ok ] HT-WPS Breaker By Silent Ghost X.

             [+] Try again (Y)es or (N)o : 
```

**Comment by SilentGhostX** [comment]
و عليكم السلام و رحمة الله تعالى و بركاته أخي ، أنا متأكد بأنني أصلحت المشكل بالنسبة للجيل الثاني من حزمة 
Aircrack Suite 
لذلك الحل الأمثل حاليا و هو تفعيل
Monitor Mode 
يدويا ، بالإضافة ما هي نسخة
Aircrack Suite 
التي تشتغل بها و في أي توزيعة و بالتوفيق أخي إن شاء الله .

**Comment by nightyman** [comment]
Wa alaykom salam akhi,
Je m'excuse je n'ai pas de clavier arabe pour répondre.

Sinon ana kheddam b WIFISLAX 4.11.1 (akher édition) sur DVD bootable 7it ma3andich bezaf diyal espace f disque dur diyal pc bach nakhdam b version VMWARE oula bach n installih :/

F Wifislax, la version aircrack-ng est 1.2-rc2-r2666
Wifislax téléchargito men had lien : http://www.wifislax.com/liberada-wifislax-4-11-1-version-de-mantenimiento/

Ou 7awelt ndir mode monitoring en manuel mais walou... ma3raftch mnin lmouchkil !

Sma7 liya a khouya bezzaf pour dérangement. allah ijazik bel khir

**Comment by SilentGhostX** [comment]
مرحباََ أخي أعتذر على الرد لأنني لم أستعمل الأنترنيت منذ مدة ، ماشي مشكل إلا مكانتش عندك العربية في الكلافيي راه كنفهم الدارجة المغربية لأنني مغربي بطبيعة الحال ، المهم المشكل أو العيب ليس في السكريبت بل في الجيل الثاني من 
Aircrack Suite 
و الحل تقريباََ شبه سهل و هو القيام بكتابة الأوامر التالية : 
[~#] ifconfig wlan0 down
[~#] iwconfig wlan0 mode monitor
[~#] ifconfig wlan0 up 
و بهذه الأوامر تكون قد فعلت المونطور مود في wlan0
Ana 9olte like "wlan0" just like example khdem b smiya dyale interface li 3andek wa rahe ghadi activa mode monitor , kaybane li ndire hade tari9a hsane mane dake sda3e rass hadi katkhdem m3a kolchi , Mohim Good Luck Bro :+1:

**Comment by nightyman** [comment]
Choukrane khouya hta ana maghribi
l3ezz ou tbarkellah 3lik !
Pour l'astuce, elle marche :+1: et c'est vrai ... l9it f d'autres forums que Aircrack li mennou lmouchkil.
Merci encore une fois !

**Comment by serpenti89** [comment]
sur cet ecran vous pouvez choisir une interface wifi supplémentaire mais vous n'en avez pas d'autre en moment wifislax
