### ISSUE TITLE
Impossible to find network with HT-WPS-Breaker

### ISSUE THREAD

**Issue by SnowPatrolXV** [SilentGhostX/HT-WPS-Breaker#26]
Hi,

I have installed Kali and the OS is up-to-date.

I have downloaded the HT-WPS-Breaker and I have added +x right.

I launch the script with root user, I select the first item on the menu, I select the wifi interface (wlan0)
So all seems OK.

But I have any network displayed even I wait 5 minutes.

The wifi seems to be OK, the network manager displays all networks.

**Comment by SnowPatrolXV** [comment]
The issue comes from the network manager.

To fix the issue, you must shutdown the  network manager :
service network-manager stop

**Comment by hemant2703** [comment]
I restart natwork manager but it not working
