### ISSUE TITLE
Crack Hidden wireless network

### ISSUE THREAD

**Issue by thansau239** [SilentGhostX/HT-WPS-Breaker#3]
Thank for your script!!!
But when  i have WPS pin, can I  crack  any hidden wireless network?
Please help me
Thank you very much!

**Comment by SilentGhostX** [comment]
[+] Yes brother if you have the name of your target wireless network , after do those steps , you can write this following command : 

[#] reaver -i <Interface , Like : Mon0> -b <Mac Address , XX:XX:XX:XX:XX:XX > -c <Channel , like : 1> -vv -n -e "<Name Of Your Target>" -p <Pin Number>

[+] Replace every variable in the previous command with your target information wireless network .

[!] follow those steps in this video to get the Hidden SSID of your target wireless network : 
       https://www.youtube.com/watch?v=HSXEL7JmiIo

[!] Or you can use the fifth choice in the script to do all this previous things in automated way , of course if the router device is vulnerable , but I advise you to do all these things manually & Good Luck Bro .
