### ISSUE TITLE
Previously Cracked WPS Devices are not cracking, not working

### ISSUE THREAD

**Issue by maazrasheed2000** [SilentGhostX/HT-WPS-Breaker#4]
Dear,
Thanks for your efforts, it seems like you have make a wonderful tool
with automation

i am having some issues

in past i have cracked at least 7 WPS pins by using Reaver (all PINs and Password are still same)

but when i use your tool, it is unable to calculate PIN, this is happening in each Device
so i am unable to crack any WPS by your tool

then i check previously cracked PINs and Password using Reaver and other wifislax tools
they are same

kindly please help me to fix this problem, your tool is awesome
with automation and it support hidden network

but now working for me

![1](https://cloud.githubusercontent.com/assets/15028016/10360253/e8d535f0-6dbc-11e5-9e59-2d853f1ce518.jpg)
![2](https://cloud.githubusercontent.com/assets/15028016/10360252/e8c97ddc-6dbc-11e5-97a0-b67da463bc31.jpg)
![3](https://cloud.githubusercontent.com/assets/15028016/10360251/e8363694-6dbc-11e5-9383-7399f0749118.jpg)

**Comment by SilentGhostX** [comment]
You're welcome brother , but sorry because my script is support only vulnerable wireless devices , this is glance of vulnerable wireless devices : https://goo.gl/CmbctB , you can browse them & G00D Luck with another wireless devices .

**Comment by maazrasheed2000** [comment]
dear,
thanks for the reply
i am saying that, your script is working bit 10 out of 1 time
i tried it on same network, is didn't give pin
i tried it whole day, then same device's pic is recovered,

its not calculating everytime
i got i required data for pin cracking all time, bit it say pin not cracked

may by in your next version you can fix it

thanks
