### ISSUE TITLE
Possible additions

### ISSUE THREAD

**Issue by 0E800** [SilentGhostX/HT-WPS-Breaker#5]
Hello, excellent tool. By far the best Pixie helper script.

I have a few suggestions:

1) may you add automation attack? Run the script and it automatically cracks each access point?

2) may you please add other color themes? some colors don't show in the day time, some are too bright for nighttime. the current color scheme looks like Christmas colors. 

3) Change the name to High Tech  or Hi Tek. Touch is a feeling, I am touching my keyboard to type this.

Thank you again for a excellent tool. Well done.

**Comment by SilentGhostX** [comment]
You're right , thanks brother for your suggestion i will update the script as soon as i can .
