### ISSUE TITLE
Retriving beacon

### ISSUE THREAD

**Issue by sklin0er4** [SilentGhostX/HT-WPS-Breaker#7]
I tried hacking the wpa2 with wash and i kept getting stuck at retriving beacon <BSSID>.

**Comment by InnerPeaceStudios** [comment]
same on my pc

**Comment by 0E800** [comment]
Wash doesn't hack the router. It only shows the routers with WPS enabled.
Most likely your too far from any WPS router or your wireless card is not
compatible with wash tool.
